<HTML>
<HEAD>
<TITLE>CONNECTING MYSQL SERVER</TITLE>
</HEAD>
<BODY>
<?PHP
$DBHOST = 'localhost';
$DBUSER = 'guest';
$DBPASS = 'guest123';
$CONN = MYSQL_CONNECT($DBHOST, $DBUSER, $DBPASS);
IF(! $CONN )
{
DIE('COULD NOT CONNECT: '
. MYSQL_ERROR());
}
ECHO 'CONNECTED SUCCESSFULLY';
MYSQL_CLOSE($CONN);
?>
</BODY>
</HTML>